// spotless:off
package frc.robot.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj centerCollectOurSide = new ChoreoTraj(
        "centerCollectOurSide",
        OptionalInt.empty(),
        7.85624,
        new Pose2d(3.88165, 7.4133, Rotation2d.fromRadians(-3.1176)),
        new Pose2d(2.41555, 6.44387, Rotation2d.fromRadians(-0.83379))
    );
    public static final ChoreoTraj centerCollectAndShootFullPath = new ChoreoTraj(
        "centerCollectAndShootFullPath",
        OptionalInt.empty(),
        5.42061,
        new Pose2d(3.45039, 7.41189, Rotation2d.fromRadians(0)),
        new Pose2d(2.11934, 5.76138, Rotation2d.fromRadians(-1.48439))
    );
    public static final ChoreoTraj startToDepo = new ChoreoTraj(
        "startToDepo",
        OptionalInt.empty(),
        1.01727,
        new Pose2d(1.19055, 5.93022, Rotation2d.fromRadians(0)),
        new Pose2d(3.5169, 5.93022, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj shootOnlyOurSide = new ChoreoTraj(
        "shootOnlyOurSide",
        OptionalInt.empty(),
        2.82126,
        new Pose2d(2.94731, 6.09472, Rotation2d.fromRadians(0)),
        new Pose2d(0.69204, 0.69593, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj depoToHub = new ChoreoTraj(
        "depoToHub",
        OptionalInt.empty(),
        0.88621,
        new Pose2d(0.63429, 0.75171, Rotation2d.fromRadians(0)),
        new Pose2d(1.92357, 1.96364, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj CenterCollectAndShoot = new ChoreoTraj(
        "CenterCollectAndShoot",
        OptionalInt.empty(),
        4.53691,
        new Pose2d(3.55509, 7.39727, Rotation2d.fromRadians(0)),
        new Pose2d(1.88186, 7.30431, Rotation2d.fromRadians(-1.0637))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("centerCollectOurSide", centerCollectOurSide),
        Map.entry("centerCollectAndShootFullPath", centerCollectAndShootFullPath),
        Map.entry("startToDepo", startToDepo),
        Map.entry("shootOnlyOurSide", shootOnlyOurSide),
        Map.entry("depoToHub", depoToHub),
        Map.entry("CenterCollectAndShoot", CenterCollectAndShoot)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
