// spotless:off
package frc.robot.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj secondPass = new ChoreoTraj(
        "secondPass",
        OptionalInt.empty(),
        4.02979,
        new Pose2d(2.92272, 6.87738, Rotation2d.fromRadians(-1.10946)),
        new Pose2d(2.93107, 6.87738, Rotation2d.fromRadians(-1.106))
    );
    public static final ChoreoTraj stealCenter = new ChoreoTraj(
        "stealCenter",
        OptionalInt.empty(),
        4.17551,
        new Pose2d(3.45039, 7.41189, Rotation2d.fromRadians(0)),
        new Pose2d(2.98994, 6.89168, Rotation2d.fromRadians(-1.05273))
    );
    public static final ChoreoTraj quarterCenter = new ChoreoTraj(
        "quarterCenter",
        OptionalInt.empty(),
        3.72025,
        new Pose2d(4.30312, 7.41938, Rotation2d.fromRadians(0.00508)),
        new Pose2d(3.07261, 7.01629, Rotation2d.fromRadians(-0.83379))
    );
    public static final ChoreoTraj leaveOutpost = new ChoreoTraj(
        "leaveOutpost",
        OptionalInt.empty(),
        0.63028,
        new Pose2d(0.72059, 0.66885, Rotation2d.fromRadians(0)),
        new Pose2d(1.92357, 1.96364, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj depotOutpost = new ChoreoTraj(
        "depotOutpost",
        OptionalInt.empty(),
        2.58712,
        new Pose2d(2.94731, 6.09472, Rotation2d.fromRadians(0)),
        new Pose2d(0.48334, 0.86411, Rotation2d.fromRadians(1.55875))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj depotOutpost$0 = new ChoreoTraj(
        "depotOutpost",
        OptionalInt.of(0),
        0.73652,
        new Pose2d(2.94731, 6.09472, Rotation2d.fromRadians(0)),
        new Pose2d(0.77461, 5.95964, Rotation2d.fromRadians(0.0268))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj depotOutpost$1 = new ChoreoTraj(
        "depotOutpost",
        OptionalInt.of(1),
        1.8506,
        new Pose2d(0.77461, 5.95964, Rotation2d.fromRadians(0.0268)),
        new Pose2d(0.48334, 0.86411, Rotation2d.fromRadians(1.55875))
    );
    public static final ChoreoTraj depotOnly = new ChoreoTraj(
        "depotOnly",
        OptionalInt.empty(),
        0.77385,
        new Pose2d(1.19055, 5.93022, Rotation2d.fromRadians(0)),
        new Pose2d(3.5169, 5.93022, Rotation2d.fromRadians(0))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("secondPass", secondPass),
        Map.entry("stealCenter", stealCenter),
        Map.entry("quarterCenter", quarterCenter),
        Map.entry("leaveOutpost", leaveOutpost),
        Map.entry("depotOutpost", depotOutpost),
        Map.entry("depotOutpost$0", depotOutpost$0),
        Map.entry("depotOutpost$1", depotOutpost$1),
        Map.entry("depotOnly", depotOnly)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
