// spotless:off
package frc.robot.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj bumpQuarterCenter = new ChoreoTraj(
        "bumpQuarterCenter",
        OptionalInt.empty(),
        5.73289,
        new Pose2d(4.30312, 7.41938, Rotation2d.fromRadians(0.00992)),
        new Pose2d(3.03989, 7.0424, Rotation2d.fromRadians(-1.08746))
    );
    public static final ChoreoTraj bumpStealCenter = new ChoreoTraj(
        "bumpStealCenter",
        OptionalInt.empty(),
        6.57884,
        new Pose2d(3.45039, 7.41189, Rotation2d.fromRadians(0)),
        new Pose2d(2.98994, 6.89168, Rotation2d.fromRadians(-1.05273))
    );
    public static final ChoreoTraj depotOnly = new ChoreoTraj(
        "depotOnly",
        OptionalInt.empty(),
        2.59845,
        new Pose2d(3.62996, 6.04556, Rotation2d.fromRadians(0)),
        new Pose2d(1.18366, 5.46535, Rotation2d.fromRadians(-0.00016))
    );
    public static final ChoreoTraj depotThenOutpost = new ChoreoTraj(
        "depotThenOutpost",
        OptionalInt.empty(),
        6.42818,
        new Pose2d(3.61144, 6.13852, Rotation2d.fromRadians(0)),
        new Pose2d(1.56002, 1.38819, Rotation2d.fromRadians(0.71664))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj depotThenOutpost$0 = new ChoreoTraj(
        "depotThenOutpost",
        OptionalInt.of(0),
        5.21011,
        new Pose2d(3.61144, 6.13852, Rotation2d.fromRadians(0)),
        new Pose2d(0.72059, 0.65856, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj depotThenOutpost$1 = new ChoreoTraj(
        "depotThenOutpost",
        OptionalInt.of(1),
        1.21807,
        new Pose2d(0.72059, 0.65856, Rotation2d.fromRadians(0)),
        new Pose2d(1.56002, 1.38819, Rotation2d.fromRadians(0.71664))
    );
    public static final ChoreoTraj outpostOnly = new ChoreoTraj(
        "outpostOnly",
        OptionalInt.empty(),
        3.04319,
        new Pose2d(3.60624, 2.50035, Rotation2d.fromRadians(0)),
        new Pose2d(1.25451, 1.93969, Rotation2d.fromRadians(0.55366))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj outpostOnly$0 = new ChoreoTraj(
        "outpostOnly",
        OptionalInt.of(0),
        2.12178,
        new Pose2d(3.60624, 2.50035, Rotation2d.fromRadians(0)),
        new Pose2d(0.7032, 0.6692, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj outpostOnly$1 = new ChoreoTraj(
        "outpostOnly",
        OptionalInt.of(1),
        0.9214099999999998,
        new Pose2d(0.7032, 0.6692, Rotation2d.fromRadians(0)),
        new Pose2d(1.25451, 1.93969, Rotation2d.fromRadians(0.55366))
    );
    public static final ChoreoTraj outpostThenDepot = new ChoreoTraj(
        "outpostThenDepot",
        OptionalInt.empty(),
        6.69741,
        new Pose2d(3.60624, 2.50035, Rotation2d.fromRadians(0)),
        new Pose2d(1.86441, 5.98399, Rotation2d.fromRadians(-0.61719))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj outpostThenDepot$0 = new ChoreoTraj(
        "outpostThenDepot",
        OptionalInt.of(0),
        2.12251,
        new Pose2d(3.60624, 2.50035, Rotation2d.fromRadians(0)),
        new Pose2d(0.71436, 0.6692, Rotation2d.fromRadians(0))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj outpostThenDepot$1 = new ChoreoTraj(
        "outpostThenDepot",
        OptionalInt.of(1),
        4.5748999999999995,
        new Pose2d(0.71436, 0.6692, Rotation2d.fromRadians(0)),
        new Pose2d(1.86441, 5.98399, Rotation2d.fromRadians(-0.61719))
    );
    public static final ChoreoTraj quarterCenter = new ChoreoTraj(
        "quarterCenter",
        OptionalInt.empty(),
        5.86979,
        new Pose2d(4.2291, 7.4168, Rotation2d.fromRadians(0.00992)),
        new Pose2d(3.38936, 7.16424, Rotation2d.fromRadians(-1.08372))
    );
    public static final ChoreoTraj secondPass = new ChoreoTraj(
        "secondPass",
        OptionalInt.empty(),
        6.52191,
        new Pose2d(3.38936, 7.16424, Rotation2d.fromRadians(-1.08372)),
        new Pose2d(3.38936, 7.16424, Rotation2d.fromRadians(-1.08372))
    );
    public static final ChoreoTraj stealCenter = new ChoreoTraj(
        "stealCenter",
        OptionalInt.empty(),
        6.63913,
        new Pose2d(3.45039, 7.41189, Rotation2d.fromRadians(0)),
        new Pose2d(2.98994, 6.89168, Rotation2d.fromRadians(-1.05273))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("bumpQuarterCenter", bumpQuarterCenter),
        Map.entry("bumpStealCenter", bumpStealCenter),
        Map.entry("depotOnly", depotOnly),
        Map.entry("depotThenOutpost", depotThenOutpost),
        Map.entry("depotThenOutpost$0", depotThenOutpost$0),
        Map.entry("depotThenOutpost$1", depotThenOutpost$1),
        Map.entry("outpostOnly", outpostOnly),
        Map.entry("outpostOnly$0", outpostOnly$0),
        Map.entry("outpostOnly$1", outpostOnly$1),
        Map.entry("outpostThenDepot", outpostThenDepot),
        Map.entry("outpostThenDepot$0", outpostThenDepot$0),
        Map.entry("outpostThenDepot$1", outpostThenDepot$1),
        Map.entry("quarterCenter", quarterCenter),
        Map.entry("secondPass", secondPass),
        Map.entry("stealCenter", stealCenter)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
